export type Libro = { nombre: string; num: number; capitulos: number };

export const LIBROS: Libro[] = [
  { nombre: "Genesis", num: 1, capitulos: 50 }, { nombre: "Exodo", num: 2, capitulos: 40 },
  { nombre: "Levitico", num: 3, capitulos: 27 }, { nombre: "Numeros", num: 4, capitulos: 36 },
  { nombre: "Deuteronomio", num: 5, capitulos: 34 }, { nombre: "Josue", num: 6, capitulos: 24 },
  { nombre: "Jueces", num: 7, capitulos: 21 }, { nombre: "Rut", num: 8, capitulos: 4 },
  { nombre: "1 Samuel", num: 9, capitulos: 31 }, { nombre: "2 Samuel", num: 10, capitulos: 24 },
  { nombre: "1 Reyes", num: 11, capitulos: 22 }, { nombre: "2 Reyes", num: 12, capitulos: 25 },
  { nombre: "1 Cronicas", num: 13, capitulos: 29 }, { nombre: "2 Cronicas", num: 14, capitulos: 36 },
  { nombre: "Esdras", num: 15, capitulos: 10 }, { nombre: "Nehemias", num: 16, capitulos: 13 },
  { nombre: "Ester", num: 17, capitulos: 10 }, { nombre: "Job", num: 18, capitulos: 42 },
  { nombre: "Salmos", num: 19, capitulos: 150 }, { nombre: "Proverbios", num: 20, capitulos: 31 },
  { nombre: "Eclesiastes", num: 21, capitulos: 12 }, { nombre: "Cantares", num: 22, capitulos: 8 },
  { nombre: "Isaias", num: 23, capitulos: 66 }, { nombre: "Jeremias", num: 24, capitulos: 52 },
  { nombre: "Lamentaciones", num: 25, capitulos: 5 }, { nombre: "Ezequiel", num: 26, capitulos: 48 },
  { nombre: "Daniel", num: 27, capitulos: 12 }, { nombre: "Oseas", num: 28, capitulos: 14 },
  { nombre: "Joel", num: 29, capitulos: 3 }, { nombre: "Amos", num: 30, capitulos: 9 },
  { nombre: "Abdias", num: 31, capitulos: 1 }, { nombre: "Jonas", num: 32, capitulos: 4 },
  { nombre: "Miqueas", num: 33, capitulos: 7 }, { nombre: "Nahum", num: 34, capitulos: 3 },
  { nombre: "Habacuc", num: 35, capitulos: 3 }, { nombre: "Sofonias", num: 36, capitulos: 3 },
  { nombre: "Hageo", num: 37, capitulos: 2 }, { nombre: "Zacarias", num: 38, capitulos: 14 },
  { nombre: "Malaquias", num: 39, capitulos: 4 },
  { nombre: "Mateo", num: 40, capitulos: 28 }, { nombre: "Marcos", num: 41, capitulos: 16 },
  { nombre: "Lucas", num: 42, capitulos: 24 }, { nombre: "Juan", num: 43, capitulos: 21 },
  { nombre: "Hechos", num: 44, capitulos: 28 }, { nombre: "Romanos", num: 45, capitulos: 16 },
  { nombre: "1 Corintios", num: 46, capitulos: 16 }, { nombre: "2 Corintios", num: 47, capitulos: 13 },
  { nombre: "Galatas", num: 48, capitulos: 6 }, { nombre: "Efesios", num: 49, capitulos: 6 },
  { nombre: "Filipenses", num: 50, capitulos: 4 }, { nombre: "Colosenses", num: 51, capitulos: 4 },
  { nombre: "1 Tesalonicenses", num: 52, capitulos: 5 }, { nombre: "2 Tesalonicenses", num: 53, capitulos: 3 },
  { nombre: "1 Timoteo", num: 54, capitulos: 6 }, { nombre: "2 Timoteo", num: 55, capitulos: 4 },
  { nombre: "Tito", num: 56, capitulos: 3 }, { nombre: "Filemon", num: 57, capitulos: 1 },
  { nombre: "Hebreos", num: 58, capitulos: 13 }, { nombre: "Santiago", num: 59, capitulos: 5 },
  { nombre: "1 Pedro", num: 60, capitulos: 5 }, { nombre: "2 Pedro", num: 61, capitulos: 3 },
  { nombre: "1 Juan", num: 62, capitulos: 5 }, { nombre: "2 Juan", num: 63, capitulos: 1 },
  { nombre: "3 Juan", num: 64, capitulos: 1 }, { nombre: "Judas", num: 65, capitulos: 1 },
  { nombre: "Apocalipsis", num: 66, capitulos: 22 },
];
